region           = "us-east-1"
vpc_cidr         = "10.0.0.0/16"
public_subnets   = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets  = ["10.0.11.0/24", "10.0.12.0/24"]
alb_name = "EA-ALB"
target_group_name="EA-alb-Backend-DEV-tg"
cluster_name     = "platform-dev-ecs"
eks_cluster_name = "platform-dev-eks"
eks_cluster_version = 1.29
service_name     = "java-app-service-v2"
task_name        = "java-app-task-v2"
image            = "your image uri here"
desired_count    = 1